<?php

use Illuminate\Database\Seeder;

class Artist_Playlist extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('artist_playlist')->insert([
            'playlist_id'=>1,
            'artist_id'=>1
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>1,
            'artist_id'=>2
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>1,
            'artist_id'=>3
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>1,
            'artist_id'=>4
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>1,
            'artist_id'=>5
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>1,
            'artist_id'=>6
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>1,
            'artist_id'=>7
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>2,
            'artist_id'=>8
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>2,
            'artist_id'=>4
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>2,
            'artist_id'=>6
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>2,
            'artist_id'=>9
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>2,
            'artist_id'=>10
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>3,
            'artist_id'=>11
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>3,
            'artist_id'=>12
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>3,
            'artist_id'=>7
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>3,
            'artist_id'=>9
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>3,
            'artist_id'=>10
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>4,
            'artist_id'=>1
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>4,
            'artist_id'=>5
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>4,
            'artist_id'=>13
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>4,
            'artist_id'=>14
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>4,
            'artist_id'=>15
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>4,
            'artist_id'=>16
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>4,
            'artist_id'=>17
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>4,
            'artist_id'=>18
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>4,
            'artist_id'=>19
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>5,
            'artist_id'=>5
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>5,
            'artist_id'=>8
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>5,
            'artist_id'=>10
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>5,
            'artist_id'=>13
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>5,
            'artist_id'=>16
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>5,
            'artist_id'=>17
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>5,
            'artist_id'=>20
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>6,
            'artist_id'=>5
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>6,
            'artist_id'=>6
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>6,
            'artist_id'=>7
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>6,
            'artist_id'=>11
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>6,
            'artist_id'=>14
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>6,
            'artist_id'=>10
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>7,
            'artist_id'=>15
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>7,
            'artist_id'=>18
        ]);
        DB::table('artist_playlist')->insert([
            'playlist_id'=>7,
            'artist_id'=>19
        ]);
    }
}
